site_name: LAMig Group Blog
site_url: https://mydomain.org/
nav:
  - CS 191/192 Deliverables: index.md
  - Backup/Reinstall Procedures: Backup.md
  - User's Manual: UserManual.md
  - Development Installation Instructions: DevInstallation.md
  - Digital Ocean Setup Guide: DOSetup.md
  - Production Update: ProdUpdate.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
  palette:
    - scheme: default
      toggle: 
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode